### PR TITLE
Made print statements Python 3 compatible

### PR DESCRIPTION
**Pull request by heijnsre**
This package looks excactly what I was looking for. The only thing is that it can't be used with Python 3 / Django 2.0 without changing these print statements.

### CODE REVIEW

**Comment by maoaiz** [comment]
Thanks @heijnsre 

Later I'll update the pypi package. Let me some days to do that.

**Comment by heijnsre** [comment]
I'm looking forward to that. Thanks for the great work.

**Comment by heijnsre** [comment]
Hi Mauricio,

I’d really like to upgrade the package using pip. Do you think you are able to update the pypi package soon? I’d appreciate that greatly.


Met vriendelijke groet,
René van Heijnsbergen
Senior Developer
T-MC
Gebouw “Bij Jacob”
Jaap Bijzerweg 19
3446 CR Woerden
0652327341
Rene.vanHeijnsbergen@t-mc.nl
www.t-mc.nl
T-MC
Wil je ook minder stress en meer plezier in je werk? Schrijf je dan nu in voor de GO training. Klik
hiervoor meer informatie en inschrijven.

Van: Mauricio <notifications@github.com>
Verzonden: woensdag 6 juni 2018 01:33
Aan: maoaiz/django-admin-conf-vars <django-admin-conf-vars@noreply.github.com>
CC: René van Heijnsbergen <Rene.vanHeijnsbergen@t-mc.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [maoaiz/django-admin-conf-vars] Made print statements Python 3 compatible (#1)


Thanks @heijnsre<https://github.com/heijnsre>

Later I'll update the pypi package. Let me some days to do that.

**Comment by maoaiz** [comment]
Hi @heijnsre 

We have a new version of `django-admin-conf-vars`.
Now you can download this repository using pip. Please [read the docs](https://pypi.org/project/django-admin-conf-vars/).

**Comment by heijnsre** [comment]
Hi @maoaiz ,

I've seen that you cleaned up a bit, and added logging. Very nice. The upgrade using pip worked like a charm. Keep up the great work.

**Pull request merged**
